### PR TITLE
Fixes map2 and map3 while improving error messages

### LINKED ISSUE #22: Better error messages for missing columns
When a column is missing, the function `errorToString` produces extremely repetitive output:

```
I saw 5 problems while decoding this CSV:

There was a problem on row 1, in the `foo` field: The `foo` field wasn't provided in the field names.

There was a problem on row 2, in the `foo` field: The `foo` field wasn't provided in the field names.

There was a problem on row 3, in the `foo` field: The `foo` field wasn't provided in the field names.

There was a problem on row 4, in the `foo` field: The `foo` field wasn't provided in the field names.

There was a problem on row 5, in the `foo` field: The `foo` field wasn't provided in the field names.
```

(This can easily lead to thousands of lines of error output), even though the error is only on the first line.

[See this Ellie for a minimal example](https://ellie-app.com/f46zsWHwW7Za1).

### LINKED ISSUE #32: `map2`, `map3` and friends don't preserve all error messages
For instance:

```elm
decoder =
    Decode.map3 (\a b c -> ( a, b, c ))
        (Decode.field "bar" Decode.int)
        (Decode.field "foo" Decode.int)
        (Decode.column 3 Decode.int)


contents =
    """bar
1
2
d
d
5
"""

Decode.decodeCsv Decode.FieldNamesFromFirstRow decoder contents
```

You would expect that for rows 1,2, and 5 you would get 2 errors (foo not provided, column 3 not found) and 3 errors for rows 3 and 4, but instead you just get 1 error for each row.

This is because they are implemented as `Result.map2`, `Result.map3` etc, which only take the first encountered error, rather than aggregating them as a list.

### PR DESCRIPTION
**Pull request by gampleman**
Fixes #32. Fixes #22. Closes #31.

This has a fairly sever refactor of the error handling, but the outcome is that `map2` and friends don't loose errors, and `oneOf` has easier to understand error messages (which are also more explicitely represented in the types).

### CODE REVIEW

**Comment by BrianHicks** [comment]
Is this an alternate take on https://github.com/BrianHicks/elm-csv/pull/31, similar to how you opened two PRs with optional field approaches?

**Comment by gampleman** [comment]
Sort of. It incorporates most of the approach of #31, but since this also changes the error type, the 2 PRs are not mutually compatible. 

The main differences on error handling side is:

- `oneOf` errors are made more explicit in that we make it clear to the user that they only need to fix one of the errors, not necessarily all the errors (which neither the existing code nor #31 do)
- Your comment about sorting by row is incorporated (we first sort by type to enable the grouping calculation, but then the grouped errors are sorted by starting row of the range).
- This also includes some tests, but these could be easily back ported to #31.

**Comment by gampleman** [comment]
Hi @BrianHicks. Sorry I dropped the ball on these PRs as I had them working in our vendored version and I completely forget these existed. I think this one is now good to go?

**Comment by BrianHicks** [comment]
nice. This got buried in my inbox but I'm slowly digging myself out and I'll try and make time to review it soon!

**Comment by BrianHicks** [comment]
well, looks like I added a reminder task to "start in two weeks" instead of "get this reviewed in the next two weeks." Sorry for the delay. I'm looking at it now.

File: src/Csv/Decode.elm [hunk 1]
```diff
@@ -341,9 +319,10 @@ type Location
     decodeCsv NoFieldNames (column 100 float) "3.14"
     --> Err
     -->     (DecodingErrors
-    -->         [ { row = 0
+    -->         [ FieldDecodingError
+    -->           { row = 0
     -->           , column = Column 100
-    -->           , problems = [ ColumnNotFound 100 ]
+    -->           , problem =  ColumnNotFound 100
```
Comment (BrianHicks) [inline src/Csv/Decode.elm]: nitpick: double space here

```suggestion
    -->           , problem = ColumnNotFound 100
```

File: src/Csv/Decode.elm [hunk 2]
```diff
@@ -549,19 +528,28 @@ Some more detail:
...
+    is a specific [`Problem`](#Problem) in a specific location.
+  - A result of a [`oneOf`](#oneOf) where all branches failed (`OneOfDecodingError`).
+  - A problem with the header row or configuration where a column is simply
+    missing (`FieldNotProvided`).
+
+-}
+type DecodingError
+    = FieldDecodingError { row : Int, column : Column, problem : Problem }
+    | OneOfDecodingError Int (List DecodingError)
+    | FieldNotProvided String
```
Comment (BrianHicks) [inline src/Csv/Decode.elm:552]: do you think it makes sense to merge this and `NoFieldNamesOnFirstRow`? Or at least to move that constructor in here?

**Review by BrianHicks — CHANGES_REQUESTED** [review]

File: src/Csv/Decode.elm (hunk 2 above)
Comment (gampleman) [reply src/Csv/Decode.elm:552]: Oh gosh, it's been a long time.

Probably? I guess if we just removed `NoFieldNamesOnFirstRow`, then if you provided an empty `CSV` you would get a `FieldNotProvided columnName` for every column you tried to decode? That seems reasonable enough UX wise unless you're decoding an ungodly amount of columns.

The alternative would be to rename this `ExpectedFieldNamesButGotEmptyFile` or some such, since that's the actual only way you can get this error.

Comment (BrianHicks) [reply src/Csv/Decode.elm:552]: > Oh gosh, it's been a long time.

Yeah, I know. Sorry. 😞 

> The alternative would be to rename this `ExpectedFieldNamesButGotEmptyFile` or some such, since that's the actual only way you can get this error.

The thing for me is that this error case is only relevant in this specific scenario. If you're not using field names, or they aren't on the first row, then it doesn't make sense to handle.

On the other hand, almost every CSV I've ever touched has had the names in the first row. It's simply too convenient, and doesn't let the metadata get out of sync with the data. So this is going to be by-far the most common option.

I dunno. I could see either way being fine. I just wondered about fixing this little design bug while we're gonna have to make a major change anyway.

I think I've just talked myself into it being fine, though, so I'm just gonna merge this. 😆

**Review by BrianHicks — APPROVED** [review]

**Comment by BrianHicks** [comment]
Thanks so much for taking care of this issue. It's been an annoyance for a while and I'm glad it's gonna get better. ❤️
